% -------------------------------------------------------------------
%  Generated by MATLAB on 20-Apr-2023 13:39:22
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
                                         

smiData = struct;
smiData.RigidTransform = struct;
smiData.RigidTransform(1).translation = ...
  [1.3577530373185076 0.15748032244054461 0.57233507236200865];
smiData.RigidTransform(1).angle = 2.0943951023931953;
smiData.RigidTransform(1).axis = [0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(1).ID = 'B[Gear2-2:-:Gear1-1]';
smiData.RigidTransform(2).translation = ...
  [0.084947581141195633 0.15748032244132942 -0.36784092889088549];
smiData.RigidTransform(2).angle = 2.6197977743201446;
smiData.RigidTransform(2).axis = [0.2669827206131053 0.68143973574109906 ...
                                  -0.68143973574126537];
smiData.RigidTransform(2).ID = 'F[Gear2-2:-:Gear1-1]';
smiData.RigidTransform(3).translation = ...
  [0.19685041680052071 1.1023622387506842 2.0472439872383825];
smiData.RigidTransform(3).angle = 2.0943951023931953;
smiData.RigidTransform(3).axis = [0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(3).ID = 'B[Palm-1:-:Gear1-1]';
smiData.RigidTransform(4).translation = ...
  [0.57258847406280289 -1.8540724511240114E-14 0.57226739567381446];
smiData.RigidTransform(4).angle = 2.0943951023931953;
smiData.RigidTransform(4).axis = [0.57735026918962584 -0.57735026918962618 ...
                                  0.5773502691896254];
smiData.RigidTransform(4).ID = 'F[Palm-1:-:Gear1-1]';
smiData.RigidTransform(5).translation = ...
  [1.7829651497011132 0.15748032244054297 0.57233529765025959];
smiData.RigidTransform(5).angle = 2.0943951023931953;
smiData.RigidTransform(5).axis = [0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(5).ID = 'B[Gear1-1:-:Gripper-2]';
smiData.RigidTransform(6).translation = ...
  [-0.15748032244056476 0.19689667813668887 2.3743002991049469];
smiData.RigidTransform(6).angle = 2.0943951023931953;
smiData.RigidTransform(6).axis = [0.57735026918962551 0.57735026918962584 ...
                                  0.57735026918962606];
smiData.RigidTransform(6).ID = 'F[Gear1-1:-:Gripper-2]';
smiData.RigidTransform(7).translation = ...
  [1.2559053267906353 0 2.0472440452150811];
smiData.RigidTransform(7).angle = 2.0943951023931953;
smiData.RigidTransform(7).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                  -0.57735026918962584];
smiData.RigidTransform(7).ID = 'B[Palm-1:-:Gear2-2]';
smiData.RigidTransform(8).translation = ...
  [1.3577530373168971 -1.1023622387514889 0.57233507236649217];
smiData.RigidTransform(8).angle = 2.094395102393487;
smiData.RigidTransform(8).axis = [-0.57735026918972276 -0.57735026918967958 ...
                                  -0.57735026918947485];
smiData.RigidTransform(8).ID = 'F[Palm-1:-:Gear2-2]';
smiData.RigidTransform(9).translation = ...
  [0.15754802173966292 0.15748032244054461 0.73060724961137558];
smiData.RigidTransform(9).angle = 2.0943951023931953;
smiData.RigidTransform(9).axis = [0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(9).ID = 'B[Gear2-2:-:Gripper-1]';
smiData.RigidTransform(10).translation = ...
  [0.49212600991898725 0.19689667811977274 2.3743002990965238];
smiData.RigidTransform(10).angle = 2.0943951023935448;
smiData.RigidTransform(10).axis = [-0.57735026918953125 -0.57735026918974219 ...
                                   0.57735026918960386];
smiData.RigidTransform(10).ID = 'F[Gear2-2:-:Gripper-1]';
smiData.RigidTransform(11).translation = ...
  [0 1.8110236220472442 0];
smiData.RigidTransform(11).angle = 2.0943951023931953;
smiData.RigidTransform(11).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(11).ID = 'B[Base-6:-:Waist-2]';
smiData.RigidTransform(12).translation = ...
  [1.9094488038429778 -0.39370078740157455 1.9094488128783229];
smiData.RigidTransform(12).angle = 2.0943951023931953;
smiData.RigidTransform(12).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(12).ID = 'F[Base-6:-:Waist-2]';
smiData.RigidTransform(13).translation = ...
  [0 0 0];
smiData.RigidTransform(13).angle = 2.0943951023931953;
smiData.RigidTransform(13).axis = [0.57735026918962584 -0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(13).ID = 'B[Base-6:-:]';
smiData.RigidTransform(14).translation = ...
  [0 0 0];
smiData.RigidTransform(14).angle = 3.1415926535897931;
smiData.RigidTransform(14).axis = [0.70710678118654757 -0.70710678118654757 ...
                                   5.5511151231257839E-17];
smiData.RigidTransform(14).ID = 'F[Base-6:-:]';
smiData.RigidTransform(15).translation = ...
  [0.90551193115582651 0 2.8346456409580956];
smiData.RigidTransform(15).angle = 2.0943951023931953;
smiData.RigidTransform(15).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(15).ID = 'B[Palm-1:-:Grip link-1]';
smiData.RigidTransform(16).translation = ...
  [0.15772580809010972 1.259842561192249 0.15743891482351269];
smiData.RigidTransform(16).angle = 2.0943951023933596;
smiData.RigidTransform(16).axis = [0.57735026918968047 -0.57735026918975607 ...
                                   0.57735026918944077];
smiData.RigidTransform(16).ID = 'F[Palm-1:-:Grip link-1]';
smiData.RigidTransform(17).translation = ...
  [0.51151981331825058 0 2.8349952108901824];
smiData.RigidTransform(17).angle = 2.0943951023931953;
smiData.RigidTransform(17).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(17).ID = 'B[Palm-1:-:Grip link-2]';
smiData.RigidTransform(18).translation = ...
  [0.15772580808142023 -1.1023622387506817 0.15743891480592032];
smiData.RigidTransform(18).angle = 2.094395102393197;
smiData.RigidTransform(18).axis = [-0.57735026918962618 -0.57735026918962562 ...
                                   -0.57735026918962551];
smiData.RigidTransform(18).ID = 'F[Palm-1:-:Grip link-2]';
smiData.RigidTransform(19).translation = ...
  [0.23892575436614466 -0.22943141484710766 1.1023622047244093];
smiData.RigidTransform(19).angle = 3.1415926535897931;
smiData.RigidTransform(19).axis = [1 0 0];
smiData.RigidTransform(19).ID = 'B[Wrist-2:-:Palm-1]';
smiData.RigidTransform(20).translation = ...
  [0.55118111937534575 0.55118091681835613 0.55118102984843309];
smiData.RigidTransform(20).angle = 2.0943951023931957;
smiData.RigidTransform(20).axis = [0.57735026918962584 0.57735026918962584 ...
                                   0.57735026918962562];
smiData.RigidTransform(20).ID = 'F[Wrist-2:-:Palm-1]';
smiData.RigidTransform(21).translation = ...
  [0.00022205078608707678 1.5856883621434488 1.3614761621111964];
smiData.RigidTransform(21).angle = 2.0943951023931953;
smiData.RigidTransform(21).axis = [0.57735026918962584 0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(21).ID = 'B[Waist-2:-:Arm 01-1]';
smiData.RigidTransform(22).translation = ...
  [-0.370643509069868 1.0262861881173342 -1.7517464836572358];
smiData.RigidTransform(22).angle = 1.0623534945633305E-15;
smiData.RigidTransform(22).axis = [-0.56094515584038718 0.82785296528985386 ...
                                   -2.4666791666538541E-16];
smiData.RigidTransform(22).ID = 'F[Waist-2:-:Arm 01-1]';
smiData.RigidTransform(23).translation = ...
  [-0.3706435090698687 5.7506964113272874 0.82677165354330739];
smiData.RigidTransform(23).angle = 3.1415926535897931;
smiData.RigidTransform(23).axis = [1 0 0];
smiData.RigidTransform(23).ID = 'B[Arm 01-1:-:Arm 02-1]';
smiData.RigidTransform(24).translation = ...
  [0.75934166079159837 0.99409431154817485 -0.575661971050458];
smiData.RigidTransform(24).angle = 7.1642189398370465E-16;
smiData.RigidTransform(24).axis = [-0.93666271962722336 -0.35023270786797384 ...
                                   1.1751107273807967E-16];
smiData.RigidTransform(24).ID = 'F[Arm 01-1:-:Arm 02-1]';
smiData.RigidTransform(25).translation = ...
  [0 4.5275591372504937 0];
smiData.RigidTransform(25).angle = 2.0943951023931953;
smiData.RigidTransform(25).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(25).ID = 'B[Arm 02-1:-:Wrist-2]';
smiData.RigidTransform(26).translation = ...
  [0.80493606554389174 -1.3317936195715172 0.88082145854619842];
smiData.RigidTransform(26).angle = 2.0943951023931953;
smiData.RigidTransform(26).axis = [-0.57735026918962573 0.57735026918962573 ...
                                   0.57735026918962573];
smiData.RigidTransform(26).ID = 'F[Arm 02-1:-:Wrist-2]';
smiData.RigidTransform(27).translation = ...
  [1.3779527589891356 0 0.15748026252596148];
smiData.RigidTransform(27).angle = 2.0943951023931953;
smiData.RigidTransform(27).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(27).ID = 'B[Grip link-1:-:Gripper-1]';
smiData.RigidTransform(28).translation = ...
  [0.4921260099192013 0.196850641002019 1.5084175013389571];
smiData.RigidTransform(28).angle = 2.0943951023935439;
smiData.RigidTransform(28).axis = [-0.57735026918953158 -0.57735026918974186 ...
                                   0.57735026918960375];
smiData.RigidTransform(28).ID = 'F[Grip link-1:-:Gripper-1]';
smiData.RigidTransform(29).translation = ...
  [1.3779527589891356 0 0.15748026252596148];
smiData.RigidTransform(29).angle = 2.0943951023931953;
smiData.RigidTransform(29).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(29).ID = 'B[Grip link-2:-:Gripper-2]';
smiData.RigidTransform(30).translation = ...
  [-7.7715611723760958E-16 0.19685064102019367 1.5084175013473846];
smiData.RigidTransform(30).angle = 2.0943951023931953;
smiData.RigidTransform(30).axis = [-0.57735026918962584 -0.57735026918962551 ...
                                   0.577350269189626];
smiData.RigidTransform(30).ID = 'F[Grip link-2:-:Gripper-2]';
smiData.RigidTransform(31).translation = ...
  [0 0 0];
smiData.RigidTransform(31).angle = 1.5707963267948966;
smiData.RigidTransform(31).axis = [1 0 0];
smiData.RigidTransform(31).ID = 'RootGround[Base-6]';
smiData.Solid = struct;
smiData.Solid(1).mass = 0.14933364329298229;
smiData.Solid(1).CoM = [0 31.449148642429829 0];
smiData.Solid(1).MoI = [183.32953944035179 245.31110128757621 183.32953944035191 ...
                        ];
smiData.Solid(1).PoI = [0 0 0];
smiData.Solid(1).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'Base*:*Default';
smiData.Solid(2).mass = 0.050151160141793834;
smiData.Solid(2).CoM = [19.330046210839175 64.4409492682662 13.78695440624338 ...
                        ];
smiData.Solid(2).MoI = [54.345614872831071 9.27043978522324 57.885801376549693 ...
                        ];
smiData.Solid(2).PoI = [-0.28623879934689794 9.6355482241080844E-5 -0.10228270088952147 ...
                        ];
smiData.Solid(2).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(2).opacity = 1;
smiData.Solid(2).ID = 'Arm 02*:*Default';
smiData.Solid(3).mass = 0.073079237725523771;
smiData.Solid(3).CoM = [-9.414394329314403 86.068824227326658 8.5348271379032479 ...
                        ];
smiData.Solid(3).MoI = [116.59565869719646 9.42810094418907 121.11603701094593 ...
                        ];
smiData.Solid(3).PoI = [0.025131912391056548 4.6345290730344466E-5 2.40472433166336E-5 ...
                        ];
smiData.Solid(3).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(3).opacity = 1;
smiData.Solid(3).ID = 'Arm 01*:*Default';
smiData.Solid(4).mass = 0.068010395426872747;
smiData.Solid(4).CoM = [42.063657521337355 17.289010130875553 47.128662453345271 ...
                        ];
smiData.Solid(4).MoI = [58.088912711816867 54.623931822118237 44.981700903393296 ...
                        ];
smiData.Solid(4).PoI = [6.2378598601889719 -0.64136861355811936 5.1749789811239859 ...
                        ];
smiData.Solid(4).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(4).opacity = 1;
smiData.Solid(4).ID = 'Waist*:*Default';
smiData.Solid(5).mass = 0.0026393672892997375;
smiData.Solid(5).CoM = [20.118505365038779 2.0000000949949022 13.936632574193281 ...
                        ];
smiData.Solid(5).MoI = [0.0898643552003102 0.446617492702613 0.36379145094237253 ...
                        ];
smiData.Solid(5).PoI = [0 -0.0092332884647123754 0];
smiData.Solid(5).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(5).opacity = 1;
smiData.Solid(5).ID = 'Gear1*:*Default';
smiData.Solid(6).mass = 0.018245359110721275;
smiData.Solid(6).CoM = [6.4992240850546548 -15.14841095426392 19.709449152742121 ...
                        ];
smiData.Solid(6).MoI = [3.9683123135402103 2.7101370981774471 5.2304419311952017 ...
                        ];
smiData.Solid(6).PoI = [-0.478256227404781 -0.0016236859116251026 -0.0054209373304788134 ...
                        ];
smiData.Solid(6).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(6).opacity = 1;
smiData.Solid(6).ID = 'Wrist*:*Default';
smiData.Solid(7).mass = 0.0025636687899806255;
smiData.Solid(7).CoM = [28.788421578375758 2.0000000949949031 14.678909200743322 ...
                        ];
smiData.Solid(7).MoI = [0.0966799635723141 0.44554196544279506 0.35569845262652389 ...
                        ];
smiData.Solid(7).PoI = [0 0.044607218032222527 0];
smiData.Solid(7).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(7).opacity = 1;
smiData.Solid(7).ID = 'Gear2*:*Default';
smiData.Solid(8).mass = 0.015717812376470908;
smiData.Solid(8).CoM = [15.976144460150321 19.817938955045417 37.554031633640264 ...
                        ];
smiData.Solid(8).MoI = [7.2434387090443453 8.1114368670773231 2.5590989301373863 ...
                        ];
smiData.Solid(8).PoI = [-1.3634796836129031 -1.4278206838428265 -0.35016743699482722 ...
                        ];
smiData.Solid(8).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(8).opacity = 1;
smiData.Solid(8).ID = 'Palm*:*Default';
smiData.Solid(9).mass = 0.00079829291634011927;
smiData.Solid(9).CoM = [19.499702258029114 2.0000000949949022 4.0000509132035909 ...
                        ];
smiData.Solid(9).MoI = [0.003627082860321137 0.10427661048130182 0.10277830893344436 ...
                        ];
smiData.Solid(9).PoI = [0 6.2620929616784411E-7 0];
smiData.Solid(9).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(9).opacity = 1;
smiData.Solid(9).ID = 'Grip link*:*Default';
smiData.Solid(10).mass = 0.0053968774113965466;
smiData.Solid(10).CoM = [4.2500002309679985 9.5134760940672862 33.421652524676652 ...
                         ];
smiData.Solid(10).MoI = [1.7130579739566496 1.5949281921545602 0.18311718769452354 ...
                         ];
smiData.Solid(10).PoI = [0.373112206453447 0 0];
smiData.Solid(10).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                           ];
smiData.Solid(10).opacity = 1;
smiData.Solid(10).ID = 'Gripper*:*Default';
smiData.CylindricalJoint = struct;
smiData.CylindricalJoint(1).Rz = struct;
smiData.CylindricalJoint(1).Rz.Pos = -49.339996084676386;
smiData.CylindricalJoint(1).Pz = struct;
smiData.CylindricalJoint(1).Pz.Pos = 0;
smiData.CylindricalJoint(1).ID = '[Gear1-1:-:Gripper-2]';
smiData.CylindricalJoint(2).Rz = struct;
smiData.CylindricalJoint(2).Rz.Pos = 43.175299367729217;
smiData.CylindricalJoint(2).Pz = struct;
smiData.CylindricalJoint(2).Pz.Pos = 0;
smiData.CylindricalJoint(2).ID = '[Gear2-2:-:Gripper-1]';
smiData.RevoluteJoint = struct;
smiData.RevoluteJoint(1).Rz = struct;
smiData.RevoluteJoint(1).Rz.Pos = 117.41609481595064;
smiData.RevoluteJoint(1).ID = '[Palm-1:-:Gear1-1]';
smiData.RevoluteJoint(2).Rz = struct;
smiData.RevoluteJoint(2).Rz.Pos = 109.79419588647738;
smiData.RevoluteJoint(2).ID = '[Palm-1:-:Gear2-2]';
smiData.RevoluteJoint(3).Rz = struct;
smiData.RevoluteJoint(3).Rz.Pos = -93.14807201575158;
smiData.RevoluteJoint(3).ID = '[Base-6:-:Waist-2]';
smiData.RevoluteJoint(4).Rz = struct;
smiData.RevoluteJoint(4).Rz.Pos = 117.42676840328059;
smiData.RevoluteJoint(4).ID = '[Palm-1:-:Grip link-1]';
smiData.RevoluteJoint(5).Rz = struct;
smiData.RevoluteJoint(5).Rz.Pos = -116.72086726325638;
smiData.RevoluteJoint(5).ID = '[Palm-1:-:Grip link-2]';
smiData.RevoluteJoint(6).Rz = struct;
smiData.RevoluteJoint(6).Rz.Pos = 160.45539630679303;
smiData.RevoluteJoint(6).ID = '[Wrist-2:-:Palm-1]';
smiData.RevoluteJoint(7).Rz = struct;
smiData.RevoluteJoint(7).Rz.Pos = -107.95280233110449;
smiData.RevoluteJoint(7).ID = '[Waist-2:-:Arm 01-1]';
smiData.RevoluteJoint(8).Rz = struct;
smiData.RevoluteJoint(8).Rz.Pos = -132.57274765414664;
smiData.RevoluteJoint(8).ID = '[Arm 01-1:-:Arm 02-1]';
smiData.RevoluteJoint(9).Rz = struct;
smiData.RevoluteJoint(9).Rz.Pos = 50.80787188453241;
smiData.RevoluteJoint(9).ID = '[Grip link-1:-:Gripper-1]';
smiData.RevoluteJoint(10).Rz = struct;
smiData.RevoluteJoint(10).Rz.Pos = 48.644768531982116;
smiData.RevoluteJoint(10).ID = '[Grip link-2:-:Gripper-2]';

